In [3]:
from pathlib import Path
import pandas as pd

data_path = Path("data/raw/car_prices_tr.csv")

if not data_path.exists():
    data_path = Path("../data/raw/car_prices_tr.csv")

df = pd.read_csv(data_path)

In [4]:
df.head()

,ilanBasligi,adres,il,fiyat(TRY),ilanID,ilanTarihi,marka,seri,model,kilometre(Km),...,boyaParcaDurumu,takasUygunluk,saticiTuru,aracVergisi(TRY),hasarGecmisi,orjinal_parça_sayısı,lokal_boyalı_parça_sayısı,boyalı_parça_sayısı,değişen_parça_sayısı,durumu_belirtilmemiş_parça_sayısı
0,2016 AUDİ A3 SPORTBACK 1.0 TFSI BOYASIZ/DEĞİŞE...,Aşağısoku Mh. Merkez,Bolu,1.169.000 TL,27812680,07 Nisan 2025,Audi,A3,A3 Sportback 1.0 TFSI Dynamic,2016.0,...,Orjinal Sağ Arka Çamurluk Arka Kaput Sol Ar...,Takasa Uygun,NaN,NaN,NaN,13,0,0,0,0
1,2018 AUDİ A6 2.0 TDI QUATTRO SUNROOF MATRİX VA...,Güneşevler Mh. Altındağ,Ankara,2.450.000 TL,28816234,07 Nisan 2025,Audi,A6,A6 Sedan 2.0 TDI Quattro,2018.0,...,Orjinal Arka Kaput Sağ Arka Kapı Sağ Ön Kap...,Takasa Uygun Değil,Galeriden,NaN,tutarı belirtilmemiş,8,0,4,1,0
2,Sahibinden Audi A4 Sedan 1.8 TFSI 2011 Model,Burmalı Mh. Merkez,Afyonkarahisar,750.000 TL,28781662,08 Nisan 2025,Audi,A4,A4 Sedan 1.8 TFSI,2011.0,...,Orjinal Tavan Sol Ön Kapı Motor Kaputu Ön ...,Takasa Uygun Değil,Sahibinden,2.013,75.000,5,2,6,0,0
3,2016 AUDI A3 AMBİENTE *CAM TAVAN LED XENON HIZ...,Ilıca Mh. Manavgat,Antalya,1.195.000 TL,28731117,03 Nisan 2025,Audi,A3,A3 Sportback 1.6 TDI Ambiente,2016.0,...,Orjinal Sağ Arka Çamurluk Arka Kaput Sağ Ar...,Takasa Uygun,Galeriden,1.606,tutarı yok,11,1,0,1,0
4,Sahibinden Audi A3 Sportback 1.6 TDI S-Line 20...,Uğur Mumcu Mh. Yenimahalle,Ankara,822.000 TL,28393351,02 Nisan 2025,Audi,A3,A3 Sportback 1.6 TDI Attraction,2012.0,...,Orjinal Sağ Arka Çamurluk Arka Kaput Sol Ar...,NaN,NaN,NaN,tutarı belirtilmemiş,12,1,0,0,0

In [5]:
df[["kilometre(Km)", "yıl"]].head(10)

   kilometre(Km)         yıl
0         2016.0  120.000 km
1         2018.0  136.000 km
2         2011.0  285.000 km
3         2016.0  101.000 km
4         2012.0  212.000 km
5         2018.0   85.600 km
6         2014.0  218.000 km
7         2018.0  126.000 km
8         2008.0  189.000 km
9         2017.0  159.500 km

In [6]:
df["gercek_yil"] = df["kilometre(Km)"]
df["gercek_km"] = df["yıl"]

In [7]:
df[["gercek_yil", "gercek_km"]].head(10)

   gercek_yil   gercek_km
0      2016.0  120.000 km
1      2018.0  136.000 km
2      2011.0  285.000 km
3      2016.0  101.000 km
4      2012.0  212.000 km
5      2018.0   85.600 km
6      2014.0  218.000 km
7      2018.0  126.000 km
8      2008.0  189.000 km
9      2017.0  159.500 km

In [8]:
df["kilometre(Km)"], df["yıl"] = df["yıl"], df["kilometre(Km)"]

In [9]:
df[["kilometre(Km)", "yıl"]].head(10)

  kilometre(Km)     yıl
0    120.000 km  2016.0
1    136.000 km  2018.0
2    285.000 km  2011.0
3    101.000 km  2016.0
4    212.000 km  2012.0
5     85.600 km  2018.0
6    218.000 km  2014.0
7    126.000 km  2018.0
8    189.000 km  2008.0
9    159.500 km  2017.0

In [10]:
df[["kilometre(Km)", "yıl", "fiyat(TRY)"]].dtypes

kilometre(Km)        str
yıl              float64
fiyat(TRY)           str
dtype: object

In [12]:
df["kilometre(Km)"] = (
    df["kilometre(Km)"]
        .str.replace(".", "", regex=False)
        .str.replace(" km", "", regex=False)
)

df["kilometre(Km)"] = pd.to_numeric(
    df["kilometre(Km)"],
    errors="coerce"
)

In [13]:
df[["kilometre(Km)", "yıl"]].head()

   kilometre(Km)     yıl
0       120000.0  2016.0
1       136000.0  2018.0
2       285000.0  2011.0
3       101000.0  2016.0
4       212000.0  2012.0

In [14]:
df[["kilometre(Km)", "yıl"]].dtypes

kilometre(Km)    float64
yıl              float64
dtype: object

In [15]:
df["fiyat(TRY)"].head(10)

0    1.169.000 TL
1    2.450.000 TL
2      750.000 TL
3    1.195.000 TL
4      822.000 TL
5    1.750.000 TL
6      990.000 TL
7    1.475.000 TL
8    1.030.000 TL
9    1.185.000 TL
Name: fiyat(TRY), dtype: str

In [16]:
df["fiyat(TRY)"] = (
    df["fiyat(TRY)"]
        .str.replace(".", "", regex=False)
        .str.replace(" TL", "", regex=False)
)

df["fiyat(TRY)"] = pd.to_numeric(
    df["fiyat(TRY)"],
    errors="coerce"
)

In [17]:
df["fiyat(TRY)"].head()

0    1169000
1    2450000
2     750000
3    1195000
4     822000
Name: fiyat(TRY), dtype: int64

In [18]:
df["fiyat(TRY)"].dtype

dtype('int64')

In [20]:
df["yıl"].isna().sum()

np.int64(1)

In [21]:
df[df["yıl"].isna()]

,ilanBasligi,adres,il,fiyat(TRY),ilanID,ilanTarihi,marka,seri,model,kilometre(Km),...,saticiTuru,aracVergisi(TRY),hasarGecmisi,orjinal_parça_sayısı,lokal_boyalı_parça_sayısı,boyalı_parça_sayısı,değişen_parça_sayısı,durumu_belirtilmemiş_parça_sayısı,gercek_yil,gercek_km
3654,2021 RENAULT ZOE ELEKTRİKLİ SERVİS BAKIMLI !!!,Turgut Özal Mh. Esenyurt,İstanbul,869000,28815064,07 Nisan 2025,Renault,Zoe,2021,NaN,...,NaN,NaN,NaN,13,0,0,0,0,NaN,Otomatik

In [22]:
df.loc[3654].to_frame(name="value")

                                                                               value
ilanBasligi                           2021 RENAULT ZOE ELEKTRİKLİ SERVİS BAKIMLI !!!
adres                                                       Turgut Özal Mh. Esenyurt
il                                                                          İstanbul
fiyat(TRY)                                                                    869000
ilanID                                                                      28815064
ilanTarihi                                                             07 Nisan 2025
marka                                                                        Renault
seri                                                                             Zoe
model                                                                           2021
kilometre(Km)                                                                    NaN
yıl                                                                              NaN
vitesTipi                                                                        NaN
yakitTuru                                                                   Elektrik
kasaTipi                                                                 Hatchback/5
renk                                                                            Mavi
motorHacmi(Cc)                                                                   NaN
motorGucu(HP)                                                           101 - 125 HP
cekisTipi                                                                        NaN
boyaParcaDurumu                    Orjinal  Sağ Arka Çamurluk  Arka Kaput  Sol Ar...
takasUygunluk                                                                    NaN
saticiTuru                                                                       NaN
aracVergisi(TRY)                                                                 NaN
hasarGecmisi                                                                     NaN
orjinal_parça_sayısı                                                              13
lokal_boyalı_parça_sayısı                                                          0
boyalı_parça_sayısı                                                                0
değişen_parça_sayısı                                                               0
durumu_belirtilmemiş_parça_sayısı                                                  0
gercek_yil                                                                       NaN
gercek_km                                                                   Otomatik

In [23]:
df = df.drop(columns=["gercek_yil", "gercek_km"])

In [24]:
df = df.drop(index=3654)

In [25]:
df = df.reset_index(drop=True)

In [26]:
df.shape

(6674, 28)

In [27]:
df["yıl"].isna().sum()

np.int64(0)

In [28]:
df["yıl"] = df["yıl"].astype(int)

In [29]:
df[["kilometre(Km)", "yıl", "fiyat(TRY)"]].head()

   kilometre(Km)   yıl  fiyat(TRY)
0       120000.0  2016     1169000
1       136000.0  2018     2450000
2       285000.0  2011      750000
3       101000.0  2016     1195000
4       212000.0  2012      822000